[config]
default_task = "hello_world"
shell = "/usr/bin/zsh"
stop_on_failure = true

[task.hello_world]
description = "Basic task to echo 'Hello, World!'"
command = "echo 'Hello, World!'"
working_dir = "."
confirm = true
timeout = 300
ignore_fail = true

[task.whoami]
description = "Another basic task to print who I am"
command = "whoami"
working_dir = "."
confirm = true
timeout = 300
ignore_fail = false