[config]
default_task = "hello_world"
shell = "powershell.exe"

[task.hello_world]
description = "Basic task to echo 'Hello, World!'"
command = "echo 'Hello, World!'"
working_dir = "C:/Users/pundt/git/forge/"
ignore_fail = true

[task.pwd]
description = "Test working_dir default"
command = "pwd"

[task.whoami]
description = "Another basic task to print who I am"
command = "whoami"
working_dir = "C:/Users/pundt/git/forge"

[task.ping]
description = "Ping google"
command = "ping -n 10 8.8.8.8"
working_dir = "C:/Users/pundt/git/forge"
confirm = true
timeout = 5
ignore_fail = true